#!/bin/bash

NAME="exe"
LIBS="-lm"
CFLAGS=""

touch makefile

echo -e "TARGET = $NAME
LIBS = $LIBS
CC = gcc
CFLAGS = $CFLAGS

.PHONY: default all clean

default: \$(TARGET)
all: default

OBJECTS = \$(patsubst %.c, %.o, \$(wildcard *.c))
HEADERS = \$(wildcard *.h)

%.o: %.c \$(HEADERS)
	\$(CC) \$(CFLAGS) -c \$< -o \$@

.PRECIOUS: \$(TARGET) \$(OBJECTS)

\$(TARGET): \$(OBJECTS)
	\$(CC) \$(OBJECTS) -Wall \$(LIBS) -o \$@
	-rm -f *.o

clean:
	-rm -f \$(TARGET)
	-rm -f *.o
" > makefile
