#!/bin/bash

input=''

stty -echo

while :
do
	echo -e "\n\n\n\n*** Sensors ***\n"
	sensors
	echo -e " "
	nvidia-smi

	echo -e "\nPress F10 to quit."

	read -t 2 -N 1 input

	if [ "~" == "$input" ]; then
		break
	fi
done

clear
stty echo
